[#59] Add CRUD endpoints for streams.
bean-pod/switchboard pull request #112
Opened 2020-10-31 22:31 UTC by FGRCL

# General info
Adds the following endpoints to the back-end service

**Issue number**: #59 

**Task description**: 
- get Streams
- get StreambyId
- create Stream
- update Stream
- delete Stream
 
# Testing

**Test coverage**:
Unit test for the controller and service layer. Mostly happy paths.

# Additional notes

**Note to reviewers**:

**To do before merging**:

2020-11-02 16:34 UTC, mohhef requested changes

2020-11-02 16:34 UTC, mohhef commented on service/switchboardapp/src/main/java/com/switchboard/app/entity/StreamEntity.java
> +@Data
We should replace Data with Setter, Getter & EqualsAndHashCode. The problem with tostring is it is infinite. It will call this.getdecoder and decoder will call this.getstream and so on.

You will face this problem when debugging the code.

More insight: https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/

2020-11-02 16:34 UTC, mohhef commented on service/switchboardapp/src/main/java/com/switchboard/app/entity/mapper/StreamMapper.java
> +}
i think mappers should deal with the entity and the dto.

1. streamdto->entity
2. streamdtos-> entity
3. streamentity ->dto

2020-11-02 16:34 UTC, mohhef commented on service/switchboardapp/src/main/java/com/switchboard/app/entity/StreamEntity.java
> +    private DecoderEntity decoder;
if you look at our ER diagram a stream is associated with an encoder and a channel.
That means that to initiate a stream you would need an encoderID, port.
In the ER diagram built it is a many to many relationship between encoder and channel.
Actually for the purpose of our application i dont think we need a new entity at all.

2020-11-02 16:34 UTC, mohhef commented on service/switchboardapp/src/main/java/com/switchboard/app/entity/StreamEntity.java
> +    private DecoderEntity decoder;
I think all we need is crud operations for the channel entity and to initiate a stream. You would have a manytomany relation from channel to encoder (which we already have on master) but add an attribute called vid which is the id of the video being streamed

2020-11-03 17:27 UTC, FGRCL commented
Github actions doesn't allow sharing secrets to fork pull request on public repositories. A new PR was made from a main repository branch with the same changes. see #122.

2020-11-03 17:29 UTC, FGRCL commented
GitHub actions doesn't allow sharing secrets to forks for public repositories. A new PR was made with the same changes, from a branch on the main repo to fix this issue. See #122

2020-11-03 17:29 UTC, closed without merging