Add page refresh to delete stream
bean-pod/switchboard pull request #260
Opened 2021-01-26 22:31 UTC by gdzooks

# General info

**Issue number**: N/A

**Task description**: 
 - Added refresh (redirect to same page) after stream delete
 
 

# Testing
**Test coverage**:
- n/a? xD

# Additional notes

**Note to reviewers**:
- @FGRCL messaged me about 6882b15 so i made the change here, since this is a small PR anyway xD

**To do before merging**:
- n/a

2021-01-29 09:51 UTC, sharon-ho approved these changes, later dismissed
LGTM!

2021-01-29 09:51 UTC, sharon-ho commented on frontend/src/streamlist/DeleteStream.jsx
> +    history.go(0);
Glad `.go(0)` was added after some discussion otherwise the page wouldn't refresh!

2021-01-29 17:23 UTC, FGRCL submitted a review, later dismissed
I tested it and it works well on my end. I just want to double check something. When I open delete a device, it throws me back to the device list page, but I can still see the device I just deleted until I refresh the page. That's expected behavior right?

2021-01-29 17:23 UTC, FGRCL commented on frontend/src/api/DeviceApi.js
> +    .delete(`${process.env.REACT_APP_DEVICE}/${deviceId}`)
Yes

2021-01-29 19:20 UTC, gdzooks commented
> I tested it and it works well on my end. I just want to double check something. When I open delete a device, it throws me back to the device list page, but I can still see the device I just deleted until I refresh the page. That's expected behavior right?

uhh you shouldn't have to refresh the page again because `history.go(0)` is already a page refresh, not sure why that's happening. could this be a delay issue with the device actually getting deleted in the backend?

2021-01-30 01:47 UTC, felixlapierre commented
This feature isn't working for me on my end :/

2021-01-30 19:21 UTC, felixlapierre requested changes
This feature wasn't working on my end since the page refreshes before the backend request can go through. I created https://github.com/bean-pod/switchboard/pull/294 with the hotfix, which should be merged into this before we merge the feature to master. I'm fixing the failing tests on the hotfix right now.

2021-01-30 20:38 UTC, felixlapierre approved these changes
My changes were applied LGTM

2021-01-30 20:50 UTC, sharon-ho approved these changes

2021-01-30 20:51 UTC, merged